name: .NET Core 8 - Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore api-transaction.sln

      - name: Build solution
        run: dotnet build api-transaction.sln --configuration Debug --no-restore

      - name: Run tests
        run: dotnet test api-transaction.test/api-transaction.test.csproj --no-build --verbosity normal
